### ISSUE TITLE
Raspberry Pi Docker Compose

### ISSUE THREAD

**Issue by mouzzampk2014** [mynttt/UpdateTool#3]
Hi, would be great if its possible to make Rapdberry Pi Image please? Thank you

**Comment by mynttt** [comment]
This sadly looks to be impossible right now. I've only seen Java 7/8 base images as Java 11 is not really supported on the Pi at the moment. Maybe in the future if Java 11 releases on the Pi and this tool is still relevant it would be possible.

**Comment by mouzzampk2014** [comment]
> This sadly looks to be impossible right now. I've only seen Java 7/8 base images as Java 11 is not really supported on the Pi at the moment. Maybe in the future if Java 11 releases on the Pi and this tool is still relevant it would be possible.

Thank you so much for reply. I will run this on Ubuntu. Is it possible to make a docker compose? Thank you so much again for keeping everyone update in reddit. Much appreciated

**Comment by mynttt** [comment]
I don't know much about docker, but a docker compose appears to be a way to manage multiple containers with one command. This utility only needs one container, so I don't know how a docker compose would be helpful here. Is there anything else a compose can do?

**Comment by mynttt** [comment]
Closed duo to inactivity.

**Comment by b2un0** [comment]
here is a working `docker-compose.yml` 

```yaml
version: '2.4'

services:
    pms:
        image: plexinc/pms-docker:beta
        restart: always
        container_name: plex
        hostname: plex
        network_mode: bridge
        mem_limit: 2048MB
        environment:
            TZ: Europe/Berlin
            PLEX_UID: 99
            PLEX_GID: 100
        ports:
            - 32400:32400/tcp
            - 33400:33400/tcp # Plex WebTools
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - /mnt/user/appdata/plex:/config
            - /mnt/user/multimedia:/mnt/user/multimedia
            - /mnt/user/appdata/plex/transcode:/transcode

    imdb_updater:
        image: mynttt/updatetool:latest
        restart: always
        network_mode: bridge
        container_name: plex_ imdb_updater
        mem_limit: 512MB
        environment:
            TZ: Europe/Berlin
            RUN_EVERY_N_HOURS: 24
            TMDB_API_KEY: XYZ
        volumes:
            - "/mnt/user/appdata/plex/Library/Application Support/Plex Media Server:/plexdata" #quoted !
            - /mnt/user/appdata/plex_imdb_updater:/config

    tautulli:
        image: tautulli/tautulli:latest
        restart: always
        container_name: tautulli
        hostname: tautulli
        network_mode: bridge
        mem_limit: 512MB
        environment:
            TZ: Europe/Berlin
            PUID: 99
            PGID: 100
        volumes:
            - /mnt/user/appdata/tautulli:/config
            - /mnt/user/appdata/plex:/plex_logs:ro
```
