### ISSUE TITLE
Only updating Movies

### ISSUE THREAD

**Issue by kicker83** [mynttt/UpdateTool#43]
Hi!

I configured my TMDB API Key and UpdateTool is only updating movies I don't know why.

I'm running it in docker and I have 1.4.5 version.

```
[INFO ] - 2020-11-19 17:16:54 @ ImdbDockerImplementation.bootstrap: TMDB API key enabled TMDB <=> IMDB matching. Will process TMDB backed Movie and TV Series libraries and TMDB orphans.

[INFO ] - 2020-11-19 17:16:57 @ ImdbRatingDatasetFactory.readData: 1092918 lines read.
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Películas 4K has 323 item(s)
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Documentales has 55 item(s)
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Infantil Peliculas has 754 item(s)
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Anime has 186 item(s)
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Películas has 2930 item(s)
[INFO ] - 2020-11-19 17:16:57 @ ImdbDockerImplementation$ImdbBatchJob.run: [MOVIE] Dolby Vision has 16 item(s)
```

Thanks!
Regards

**Comment by mynttt** [comment]
Hi!

The reason for this could be that the TV Show libraries don't use the TMDB agent (even if they have some items that are TMDB matched before the agent changed). 

To verify this you can run this query on the database file:

```sql
SELECT name, agent FROM library_sections;
```

And post the result of it here.

**Comment by x5nder** [comment]
I'm having similar isses. I went from using updatetool with flag **CAPABILITIES="NO_TV"** to flag **TVDB_API_KEY="api_key"** and I'm getting tons and tons of messages like these:

`[WARN ] - 2020-11-22 10:11:58 @ TmdbSeriesToImdbResolvement.lambda$new$1: TMDB TV Show item Attack of the Space Terrapin with id 4695/1/1 does not have an IMDB id associated. [null]
[WARN ] - 2020-11-22 10:11:58 @ TvdbToImdbResolvement.lambda$new$1: TVDB item Galvatron's Great Rampage with id 156481/1/12 does not have an IMDB id associated.
[WARN ] - 2020-11-22 10:11:58 @ TmdbSeriesToImdbResolvement.lambda$new$1: TMDB TV Show item Rescue of the Astronauts with id 4695/1/2 does not have an IMDB id associated. [null]
[WARN ] - 2020-11-22 10:11:58 @ TmdbSeriesToImdbResolvement.lambda$new$1: TMDB TV Show item The Space Serpent with id 4695/1/4 does not have an IMDB id associated. [null]
[WARN ] - 2020-11-22 10:11:58 @ TmdbSeriesToImdbResolvement.lambda$new$1: TMDB TV Show item Ghost Ship from Planet Mir with id 4695/1/5 does not have an IMDB id associated. [null]`

I tried verifying the database:

`$ sudo sqlite3 com.plexapp.plugins.library.db "SELECT name, agent FROM library_sections"
Movies|tv.plex.agents.movie
TV Shows|com.plexapp.agents.themoviedb
Videos|com.plexapp.agents.none
Movies (4K)|tv.plex.agents.movie
Talkshows|com.plexapp.agents.thetvdb`

**Comment by ajhorvath20** [comment]
Hi same happening here but I don't think its docker or config issue. There something I am missing. Only movies are updating with new ratings but TV shows are not updating at all. Here is my override 
```
  updatetool:
    image: mynttt/updatetool
    hostname: ${DOCKERHOSTNAME}
    container_name: updatetool
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_EVERY_N_HOURS=12
      - TMDB_API_KEY={TMDB_API_KEY}
      - TVDB_API_KEY=
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/updatetool:/config
      - "${DOCKERCONFDIR}/plex/Library/Application Support/Plex Media Server:/plexdata"
```
I left `TVDB_API_KEY=` empty as I don't have a API key. Is there anything I am missing. 

There are no errors in the logs tho.

Thank you
