### ISSUE TITLE
Unable to locate database file

### ISSUE THREAD

**Issue by leepeuker** [mynttt/UpdateTool#81]
Hey, I have a similar issue like reported in https://github.com/mynttt/UpdateTool/issues/77

It worked fine the last time I checked (a few months ago I think), but after updating the image today via `docker-compose pull` I got the following error:

```
plex_imdb_updater    | [ERROR] - 2022-01-02 11:20:45 @ SqliteDatabaseProvider.<init>: Unable to locate database file @ /plexdata/Plug-in Support/Databases/com.plexapp.plugins.library.db
plex_imdb_updater    | [ERROR] - 2022-01-02 11:20:45 @ SqliteDatabaseProvider.<init>: Exiting tool... Please check your configured database path...
```

My docker-compose.yml:
```
version: "3"

services:
  plex_imdb_updater:
    image: mynttt/updatetool
    container_name: plex_imdb_updater
    environment:
      - USE_PLEX_SQLITE_BINARY_FOR_WRITE_ACCESS=true
      - TMDB_API_KEY=XXX
      - RUN_EVERY_N_HOURS=6
    volumes:
      - /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server:/plexdata
      - /home/XXX/apps/plex-imdb-updater/config:/config
```

Here the prove that the db files exist at the configured path:
```
$ find /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server -name "*.db"
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.dlna.db
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.blobs.db
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.trakttv.db
```

I have tried adding `OVERRIDE_DATABASE_LOCATION=/plexdata/Plug-in Support/Databases` like suggested in the other issue, but it does not help.

**Comment by mynttt** [comment]
Very strange issue. I do not see any other way of debugging this than looking directly into the container. I have added a debug switch for that - just add the environment variable `DOCKER_DEBUG_PRINT_TREE_OF_PLEX_PATHS` and assign any non-null value to it.

On startup it will show what the two ENV variables are actually set to and also output a result of `tree`. This should help us sort out what is actually mounted to the docker and set in the environment variables.

**Comment by leepeuker** [comment]
Hey, thanks for the answer. Here is the output with DOCKER_DEBUG_PRINT_TREE_OF_PLEX_PATHS:

```
plex_imdb_updater    | *** VERSION 1.6.4 IS UP TO DATE! ***
plex_imdb_updater    | MAX JVM HEAP: -Xmx256m
plex_imdb_updater    | Enabled native Plex SQLite binary for use in write access!
plex_imdb_updater    | Plex data dir (PLEX_DATA_DIR) => /plexdata
plex_imdb_updater    | Printing tree...
plex_imdb_updater    | /plexdata
plex_imdb_updater    | ├── Logs
plex_imdb_updater    | └── Plug-in\ Support
plex_imdb_updater    |     └── Databases
plex_imdb_updater    | 
plex_imdb_updater    | 3 directories, 0 files
´´´

Seems like the directory definitly exist, but I guess there should be files in it?

**Comment by mynttt** [comment]
@leepeuker That is extremly strange. Could be a permission issue maybe or for some reasone the docker has actual files there and the files you see in the `tree` are not the mounted ones but the ones that for whatever reason exist in the container?

Maybe you can try this:

a.) Change the bind mount from /plexdata <=> <real path on your system> to /plexdata1 <=> <real path on your system>
b.) Set `OVERRIDE_DATABASE_LOCATION` to `/plexdata1/Plug-in Support/Databases` and look what happens.

**Comment by leepeuker** [comment]
Changed docker-compose.yml to 
```
version: "3"

services:
  plex_imdb_updater:
    image: mynttt/updatetool
    container_name: plex_imdb_updater
    environment:
      - USE_PLEX_SQLITE_BINARY_FOR_WRITE_ACCESS=true
      - TMDB_API_KEY=XXX
      - RUN_EVERY_N_HOURS=6
      - OVERRIDE_DATABASE_LOCATION=/plexdata1/Plug-in\ Support/Databases
    volumes:
      - /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server:/plexdata1
      - /home/XXX/apps/plex-imdb-updater/config:/config
```

got 
```
plex_imdb_updater    | Plex data dir (PLEX_DATA_DIR) => /plexdata
plex_imdb_updater    | Printing tree...
plex_imdb_updater    | /plexdata [error opening dir]
plex_imdb_updater    | 
plex_imdb_updater    | 0 directories, 0 files
plex_imdb_updater    | ===================
plex_imdb_updater    | Override database location will be used to search for DB (OVERRIDE_DATABASE_LOCATION) => /plexdata1/Plug-in\ Support/Databases
plex_imdb_updater    | Printing tree...
plex_imdb_updater    | /plexdata1/Plug-in\ [error opening dir]
plex_imdb_updater    | Support/Databases [error opening dir]
```

Seems like the debugging has a problem with maybe the white space in the path? 🤔

**Comment by mynttt** [comment]
How does this fare?

```
version: "3"

services:
  plex_imdb_updater:
    image: mynttt/updatetool
    container_name: plex_imdb_updater
    environment:
      - USE_PLEX_SQLITE_BINARY_FOR_WRITE_ACCESS=true
      - TMDB_API_KEY=XXX
      - RUN_EVERY_N_HOURS=6
      - OVERRIDE_DATABASE_LOCATION="/plexdata1/Plug-in Support/Databases"
    volumes:
      - /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server:/plexdata1
      - /home/XXX/apps/plex-imdb-updater/config:/config
```

In your case it looks like it split the space and thought it was supplied two directories (that obviously would not exist).
